### PR TITLE
Elm html@2.0.0 compliant module

### PR DESCRIPTION
**Pull request by neochrome**
Hi,
I think I managed to get most of the elm html module at v2.0.0.
The second commit contains a stab at adding support for `on` and `onWithOptions` and related helpers. I didn't dare go down into the Vdom though, so it's currently implemented in the Html2 module. I also added a test case showing off how to use it.

Should we keep the `on` and `onWithOptions` stuff, or leave it out?

### CODE REVIEW

**Comment by OvermindDL1** [comment]
> Should we keep the on and onWithOptions stuff, or leave it out?

Definitely include it as it is the Elm way, though we can definitely make a better API instead overall, such as including it in the return type so the user can calculate what those values should be based on internal data instead of just 'always' or 'never' as Elm does it, but yes definitely include the Elm style as well.  :-)

Super-thanks for the new example of the module usage to test that it works too!  :-)

It might be worth adding the `on` and `onWithOptions` to Tea_Html as well, I think it was in the older API as well, I didn't add it at the time as I really didn't like it and I had methods that could do what it did but more powerful, but I did leave the names open specifically for being added 'eventually', hmm...  You want to do that?

**Comment by neochrome** [comment]
I can definitely move on et al to Tea_html and expose them through the new
module as well, no problem :)

**Comment by neochrome** [comment]
Is this looking ok?

**Comment by OvermindDL1** [comment]
@neochrome Gorgeous!  Merging in, will test at next update (if anyone needs this functionality released to npm sooner, please ping me and I'll do so).  :-)

**Pull request merged**
