### PR TITLE
Add simple debugger and example usage as test

### PR DESCRIPTION
**Pull request by neochrome**
Initial take on a simple elmish debugger.

Right now only for `standardProgram` and implemented as a functor to get the types right.

Before merging support for `beginnerProgram` and regular record-based usage should be considered.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Looks awesome, and it looks like it will be easy to use as records as well.  :-)

**Comment by neochrome** [comment]
I think I managed to come up with something records based that might work.
Please have a look @OvermindDL1 and tell me if you think it looks ok.
If this is on the right track I'll clean up and flesh out with support for `beginnerProgram` as well.

**Comment by OvermindDL1** [comment]
It looks good, in addition to optionally beginnerProgram it definitely needs to support the normal `Program` as that is the one that all others end up delegating to as it's occasionally needed for it's power.  :-)

**Comment by neochrome** [comment]
Yeah, I'm looking into the ppx track, but it feels a bit too much to ask
people to add ppx-flags in order to get nice debugging. Probably better to
release as is abd await the possibility of additional debug printing in
upstream bucklescript...

Regards examples/tests - I'm just lazy, and that's not a good excuse - let
me add complete examples before merging?

**Comment by OvermindDL1** [comment]
> I'm just lazy, and that's not a good excuse - let
me add complete examples before merging?

Heh, I entirely relate, although I have a general lack of time on my side to blame it on...  ^.^;

Sure, if you want to do them then I'll wait.  :-)

_/me really needs to come up with a good testing infrastructure that is not so manual... should grab some of the OCaml testing libraries and see which would work best..._

**Comment by neochrome** [comment]
Hmmm, I think I might have some homebrewed rspec inspired test runner for OCaml lying around somewhere that might be useful...

**Comment by OvermindDL1** [comment]
> Hmmm, I think I might have some homebrewed rspec inspired test runner for OCaml lying around somewhere that might be useful...

You interesting in giving it a try to see how well it works for these systems?  :-)

**Comment by neochrome** [comment]
There, now all program types has their own debugging examples.

> You interesting in giving it a try to see how well it works for these systems? :-)

Sure, I'll see if I can dig it out and blow away some dust - maybe best to keep in a separate PR though.

**Comment by OvermindDL1** [comment]
All three in the example, nice!

Ready for merging or anything else you want to change?  :-)

**Comment by OvermindDL1** [comment]
Done!  I'll test in detail when I get time here in a bit and push out a release then.  :-)

**Pull request merged**
