### PR TITLE
Fix error caused by new bs 1.5.2 convention

### PR DESCRIPTION
**Pull request by jackalcooper**
https://github.com/OvermindDL1/bucklescript-tea/issues/19

### CODE REVIEW

**Comment by jackalcooper** [comment]
http://bloomberg.github.io/bucklescript/Manual#_object_label_translation_convention

**Comment by OvermindDL1** [comment]
Heh, interesting, however this breaks the elm style, which uses underscore as a trailing character to work around keywords and such, hmm...  @bobzhang Any ideas about how to get the elm syntax to work as I want as direct translations as possible?

**Comment by jackalcooper** [comment]
Yeah, to me a `_xxx` kind of implies "ignore" so it is weird to actually calling it.

**Comment by jackalcooper** [comment]
Maybe `bs.send` is a walk around? Well but as you say you want to keep Elm style.....

**Comment by bobzhang** [comment]
@OvermindDL1 The thing is `snake_case` is used pervasively in OCaml community, it was discussed before it seems everyone was on board for such change..
previously `self##hello_world` will be translated into `self.hello` which caused so many surprises(I got asked by so many people even it is documented properly).
now `self##hello_world` will be translated into `self.hello_world`, only `self##hello__` will be mangled as `self.hello`

**Comment by jackalcooper** [comment]
@bobzhang I would like to ask more about the syntax of BuckleScript. Why can't we write those bindings in a more functional manner. For instance, the up lifting:
why 
```ocaml
type t = _xmlhttprequest Js.t
```
not
```ocaml
type t = Js.t _xmlhttprequest
```
Instead we got every bs 'suffix' which breaks the functional style.
I think if the binding become more functional there will be more potential or that's what you want to prevent us from?

**Comment by bobzhang** [comment]
@jackalcooper BuckleScript does not invent syntax, it is exactly the same as OCaml. if you like such style, you can try out Reason which is also supported by BuckleScript

**Comment by OvermindDL1** [comment]
Published.  :-)

Keep sending PR's if any more issues on the new Bucklescript version!  :-)

**Pull request merged**
