### PR TITLE
Add title html attribute

### PR DESCRIPTION
**Pull request by neochrome**
I thought we should have direct access to the title html attribute

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Yep yep, quite useful, merging and it'll be in the next release (which if you need soon then please ping me otherwise I'll batch it ^.^).  :-)

Thanks much!!

Before I merge, do you want to add yourself to the contributors list so we can keep track of who has contributed?  :-)

**Comment by neochrome** [comment]
sure thing and no hurry I have implemented it locally for now :)

**Comment by OvermindDL1** [comment]
> sure thing

Cool, when you add yourself to the contributor list then I'll merge.  :-)

**Comment by OvermindDL1** [comment]
Perfect!  ^.^

Merging!  :-)

**Pull request merged**
