### PR TITLE
Adds navigational cmds to go back/fwd in history

### PR DESCRIPTION
**Pull request by neochrome**
Signed-off-by: Johan Stenqvist <johan@stenqvist.net>

### CODE REVIEW

**Comment by OvermindDL1** [comment]
I like these but the reason Elm didn't add them (at the time at least) was that they can throw errors, and consequently that should be handled here as well.  We don't want any javascript exceptions to propagate into Tea, which can halt the event loop, so the best thing would be to catch them and return either success or failure as a Result I think?  Thoughts?

**Comment by neochrome** [comment]
Hmm, I agree that errors are undesirable - I'll look into it!

**Comment by OvermindDL1** [comment]
Bucklescript lets you catch javascript errors via normal ocaml exceptions by having a special javascript exception type that you can match on, it's actually pretty easy.  :-)

The line at https://github.com/OvermindDL1/bucklescript-tea/pull/119/files#diff-4a3db9fc586527f83ce90a2400c27a86R69 should be all you need to wrap in an exception handler I'd think (the `let _ = Web.Window.(History.go window) step in` line), and honestly I'm not sure if a message should be sent back or not on success or not...  It would be best if you could have two options for that but that seems like too many calls, maybe just an optional argument (so change `let go step =` to `let go ?resultMsg step =` where `resultMsg` just takes in a boolean on success or failure, or a result object with the exception information and returns a message to feed back into the application, and if `resultMsg` isn't set then don't pass anything back to the application) or so?

**Comment by neochrome** [comment]
Are you sure that errors can be raised when navigating through history?
This page seems to indicate otherwise if I'm not mistaken?
https://developer.mozilla.org/en-US/docs/Web/API/History

**Comment by OvermindDL1** [comment]
Well first of all the History API needs to exist, the `go` call needs to exist (and on IE it can take URL's instead), and attempting to `go` before/after the first/last entries threw an exception in some browsers though I think that's "mostly" fixed now that the html5 spec states that an invalid arg is a no-op (I still have to deal with IE11 at work, had to deal with IE10 too until just recently actually, so glad that's gone....).  If we assume just evergreen support then it is fine as it is, but if an exception does happen within a callback then it will kill the entire event loop of tea, I should probably shore that up a but more so I can be less picky about that in cmd's...

I'll accept this, and leaving myself a note to handle callbacks a bit safer at the cost of an exception handler setup...

**Pull request merged**
