### PR TITLE
avoid Printf for future compatibility

### PR DESCRIPTION
**Pull request by bobzhang**
This should also produce smaller bundles.

### CODE REVIEW

**Comment by jackalcooper** [comment]
Is it possible to schedule a meeting or a discussion on forum to discuss the future admin of this project? Looks like everything is kind of outdated. It would be nice if ReScript core team can maintain this project and add it to your tests/CI (considering the codebase is not that large).
@OvermindDL1 @bobzhang

**Comment by bobzhang** [comment]
@jackalcooper I am happy to test it, let me know what I can do

**Comment by OvermindDL1** [comment]
Looks fine although its not at all OCaml'y.  ^.^;

**Comment by OvermindDL1** [comment]
@jackalcooper I'm up for it, anyone on those core teams I can give access for this or so.

**Comment by bobzhang** [comment]
Hi @OvermindDL1 , I am happy to contribute to this project. What I can do is to ensure changes in the upstream will not break this repo, I don't have the domain knowledge to contribute the UI bug fixes though

**Comment by OvermindDL1** [comment]
@bobzhang Added you as a collaborator.

The UI stuff is actually pretty trivial, the 'TEA' style is kind of a rehash of old event driven pipes, except there is a single 'pipe', lol.

**Pull request merged**
